In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [49]:
df = pd.read_csv('placementReg.csv')

In [50]:
df.head()

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [52]:
x = df.iloc[:,0:1]
y = df.iloc[:,-1]

In [85]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [94]:
class manual_reg:
    def __init__(self):
        self.m = None
        self.b = None

    def fit(self,X_train,y_train):
        num = 0
        den = 0
        
        for i in range(X_train.shape[0]):
            num = num + (X_train.iloc[i]-X_train.mean())*(y_train.iloc[i]-y_train.mean())
            den = den + (X_train.iloc[i]-X_train.mean())*(X_train.iloc[i]-X_train.mean())
        
        self.m = num/den
        self.b = y_train.mean()-(m*X_train.mean())

    def predict(self,X_test):
        return self.m*X_test + self.b

In [95]:
lr = manual_reg()

In [96]:
lr.fit(X_train,y_train)

In [97]:
lr.predict(X_test)

         cgpa
95   2.780313
15   3.136352
30   3.199521
158  2.389819
128  3.526847
115  3.768035
69   3.165065
170  2.544868
174  3.176550
45   3.492392
66   1.907444
182  2.349621
165  3.687639
78   2.757343
186  3.475164
177  3.044471
56   2.326651
152  3.205263
82   2.177344
68   3.314372
124  2.452987
16   2.900907
148  3.320115
93   2.872195
65   3.337342
60   2.194572
84   1.419326
67   2.711403
125  3.182293
132  2.326651
9    3.745064
18   2.958333
55   3.681896
75   2.975561
150  2.590809
104  3.348827
135  2.475958
137  3.073184
164  4.175757
76   2.958333