In [1]:
import requests
import pandas as pd

In [9]:
url = "https://daily-petrol-diesel-lpg-cng-fuel-prices-in-india.p.rapidapi.com/v1/fuel-prices/history/india/maharashtra/mumbai"

In [24]:
url_base = "https://daily-petrol-diesel-lpg-cng-fuel-prices-in-india.p.rapidapi.com/v1/"

In [26]:
endpoints = {
    "states": "list/india/states",
    "cities": "fuel-prices/history/india/maharashtra/mumbai"
            }

In [7]:
headers = {
    "x-rapidapi-host":"daily-petrol-diesel-lpg-cng-fuel-prices-in-india.p.rapidapi.com",
    "x-rapidapi-key":"1fbfea034bmsha54b07643f8043cp12bac3jsn63d5f4f76973"
}

In [31]:
results = {}

In [45]:
for name, endp in endpoints.items():
    url2 = url_base+endp
    response = requests.get(url2, headers=headers)
    if response.status_code == 200:
        results[name] = response.json()
    else:
        print(f"failed for {response.status_code}")

In [56]:
pd.DataFrame(results["cities"]).head()

,cityId,cityName,stateId,stateName,countryId,countryName,history
0,mumbai,Mumbai,maharashtra,Maharashtra,india,India,"{'applicableOn': '2025-07-15', 'fuel': {'petro..."
1,mumbai,Mumbai,maharashtra,Maharashtra,india,India,"{'applicableOn': '2025-07-16', 'fuel': {'petro..."
2,mumbai,Mumbai,maharashtra,Maharashtra,india,India,"{'applicableOn': '2025-07-17', 'fuel': {'petro..."
3,mumbai,Mumbai,maharashtra,Maharashtra,india,India,"{'applicableOn': '2025-07-18', 'fuel': {'petro..."
4,mumbai,Mumbai,maharashtra,Maharashtra,india,India,"{'applicableOn': '2025-07-19', 'fuel': {'petro..."

In [57]:
pd.DataFrame(results["states"]).head()

  countryId countryName                                             states
0     india       India  {'stateId': 'andaman-and-nicobar-islands', 'st...
1     india       India  {'stateId': 'andhra-pradesh', 'stateName': 'An...
2     india       India  {'stateId': 'arunachal-pradesh', 'stateName': ...
3     india       India         {'stateId': 'assam', 'stateName': 'Assam'}
4     india       India         {'stateId': 'bihar', 'stateName': 'Bihar'}

In [12]:
response = requests.get(url, headers=headers)

In [18]:
data = response.json()

In [36]:
type(response)

requests.models.Response

In [22]:
pd.DataFrame(data)["history"]

0     {'applicableOn': '2025-07-15', 'fuel': {'petro...
1     {'applicableOn': '2025-07-16', 'fuel': {'petro...
2     {'applicableOn': '2025-07-17', 'fuel': {'petro...
3     {'applicableOn': '2025-07-18', 'fuel': {'petro...
4     {'applicableOn': '2025-07-19', 'fuel': {'petro...
5     {'applicableOn': '2025-07-20', 'fuel': {'petro...
6     {'applicableOn': '2025-07-21', 'fuel': {'petro...
7     {'applicableOn': '2025-07-22', 'fuel': {'petro...
8     {'applicableOn': '2025-07-23', 'fuel': {'petro...
9     {'applicableOn': '2025-07-24', 'fuel': {'petro...
10    {'applicableOn': '2025-07-25', 'fuel': {'petro...
11    {'applicableOn': '2025-07-26', 'fuel': {'petro...
12    {'applicableOn': '2025-07-27', 'fuel': {'petro...
13    {'applicableOn': '2025-07-28', 'fuel': {'petro...
14    {'applicableOn': '2025-07-29', 'fuel': {'petro...
15    {'applicableOn': '2025-07-30', 'fuel': {'petro...
16    {'applicableOn': '2025-07-31', 'fuel': {'petro...
17    {'applicableOn': '2025-08-01', 'fuel': {'petro...
18    {'applicableOn': '2025-08-02', 'fuel': {'petro...
19    {'applicableOn': '2025-08-03', 'fuel': {'petro...
20    {'applicableOn': '2025-08-04', 'fuel': {'petro...
21    {'applicableOn': '2025-08-05', 'fuel': {'petro...
22    {'applicableOn': '2025-08-06', 'fuel': {'petro...
23    {'applicableOn': '2025-08-07', 'fuel': {'petro...
24    {'applicableOn': '2025-08-08', 'fuel': {'petro...
25    {'applicableOn': '2025-08-09', 'fuel': {'petro...
26    {'applicableOn': '2025-08-10', 'fuel': {'petro...
27    {'applicableOn': '2025-08-11', 'fuel': {'petro...
28    {'applicableOn': '2025-08-12', 'fuel': {'petro...
29    {'applicableOn': '2025-08-13', 'fuel': {'petro...
Name: history, dtype: object